# Generated by Django 5.2 on 2025-04-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebooking',
            old_name='professional',
            new_name='provider',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
