# Generated by Django 5.2 on 2025-04-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_professional_servicebooking_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
