# Generated by Django 5.2 on 2025-05-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_about_me_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='address',
        ),
    ]
